# Generated by Django 3.2.4 on 2021-06-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_info',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('nation', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
    ]
